[package]
name = "git-branch-stash"
description = "Manage snapshots of your working directory"
version = "0.9.2"
documentation = "https://github.com/gitext-rs/git-branch-stash.git"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[dependencies]
git2 = { version = "0.16", default-features = false }
git-config-env = "0.1.4"
git2-ext = "0.5.0"
log = "0.4.17"
eyre = "0.6"
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.85"
bstr = "1.3.0"
maplit = "1.0.2"
