[package]
name = "git-branch-stash"
description = "Manage snapshots of your working directory"
version = "0.9.0"
documentation = "https://github.com/gitext-rs/git-branch-stash.git"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[dependencies]
git2 = { version = "0.15", default-features = false }
git-config-env = "0.1"
git2-ext = "0.1.0"
log = "0.4"
eyre = "0.6"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bstr = "1.1"
maplit = "1"
