[package]
name = "git-branch-stash"
description = "Manage snapshots of your working directory"
version = "0.8.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gitext-rs/git-branch-stash.git"
documentation = "https://github.com/gitext-rs/git-branch-stash.git"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[dependencies]
git2 = { version = "0.14", default-features = false }
git-config-env = "0.1"
git2-ext = "0.0.5"
log = "0.4"
eyre = "0.6"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ignore = "0.4"
bstr = "0.2"
maplit = "1"
